### ISSUE TITLE
Connect to yubikey using SerialID

### ISSUE THREAD

**Issue by Cavalcantifer** [CmdrMoozy/yubirs#17]
It could be interesting to add a function to get serial of the Yubikey, like _ykpiv_get_serial_ in the _yubico-piv-tool_ : https://github.com/Yubico/yubico-piv-tool/blob/a8943a96b5630b25ccf81d02fb4ada57119717ac/lib/ykpiv.c#L1335

Moreover, a connection by Serial number would make it possible to be sure of the Yubikey on which one connects, rather than by the reader which can change.

**Comment by CmdrMoozy** [comment]
Fixed by pull request #20
